version: '3.8'

services:
  api:
    build:
      context: ./backend
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5400}
      - DB_NAME=${DB_NAME:-gestion_horas}
      - SECRET_KEY=${SECRET_KEY:-supersecretkey123456789}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID:-admin_id}
      - ADMIN_NOMBRE=${ADMIN_NOMBRE:-Administrador}
    ports:
      - "8000:8000"
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always 