version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-tu-usuario}/gestion-horas-api:${TAG:-latest}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME:-tu-usuario}/gestion-horas-frontend:${TAG:-latest} 