version: '3.8'

networks:
  traefik-public:
    external: true

services:
  api:
    image: fbermudez3e/gestion-horas-api:latest
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5400}
      - DB_NAME=${DB_NAME:-gestion_horas}
      - SECRET_KEY=${SECRET_KEY:-supersecretkey123456789}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID:-admin_id}
      - ADMIN_NOMBRE=${ADMIN_NOMBRE:-Administrador}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.horas-api.rule=Host(`api.hores.rbimprove.com`)"
        - "traefik.http.routers.horas-api.entrypoints=websecure"
        - "traefik.http.routers.horas-api.tls=true"
        - "traefik.http.routers.horas-api.tls.certresolver=letsencrypt"
        - "traefik.http.services.horas-api-service.loadbalancer.server.port=8000"
      restart_policy:
        condition: any
    networks:
      - traefik-public
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: fbermudez3e/gestion-horas-frontend:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.horas-frontend.rule=Host(`hores.rbimprove.com`)"
        - "traefik.http.routers.horas-frontend.entrypoints=websecure"
        - "traefik.http.routers.horas-frontend.tls=true"
        - "traefik.http.routers.horas-frontend.tls.certresolver=letsencrypt"
        - "traefik.http.services.horas-frontend-service.loadbalancer.server.port=80"
      restart_policy:
        condition: any
    networks:
      - traefik-public
    depends_on:
      - api